### ISSUE TITLE
Entity not updated

### ISSUE THREAD

**Issue by AraaCuteUwU** [dhnnz/TopVoteNPC#1]
When there are players who vote, the skin on the entity is not automatically updated

**Comment by dhnnz** [comment]
> Thank you for reporting the "Entity not updated" issue for the TopVoteNPC plugin on GitHub. We are happy to inform you that the issue has been fixed, and entities can now be updated without any disruptions. We appreciate your contribution and thank you for your support.

https://github.com/dhnnz/TopVoteNPC/commit/639fb502e64014048568f27219a319ac5443a3b3
